### ISSUE TITLE
CT: Assertion failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs-basics#32]
```
masses-and-springs-basics : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540212051066:575:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212051066:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212051066:1444:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212051066:1207:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212051066:381:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540212051066:187:53)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212051066:891:30)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540212051066:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540212051066:61:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
masses-and-springs-basics : xss-fuzz : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerCancel (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540206624093:594:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540206624093:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540206624093:1444:12)
    at Input.cancelEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540206624093:1304:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540206624093:425:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540206624093:187:53)
    at Input.touchCancel (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540206624093:927:33)
    at InputFuzzer.touchCancel (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540206624093:259:27)
    at InputFuzzer.touchCancelAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540206624093:66:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
```

**Comment by Denz1994** [comment]
Closing as described in https://github.com/phetsims/masses-and-springs/issues/336.
